### ISSUE TITLE
Support for VS 2022

### ISSUE THREAD

**Issue by shoaibshakeel381** [guudan/Vs-AddMultipleProjectsToSolution#8]
### Installed product versions
- Visual Studio: 2022
- This extension: 1.2.0

### Description
Can you please add support for VS 2022

**Comment by KifoPL** [comment]
I second this. Any plans on this feature? This is a huge lifesaver, I have over 30 projects I have to add manually (or via VS2019), which is inconvenient.

**Comment by SteinTheRuler** [comment]
I would really like this extension in 2022. Please update! :)

**Comment by JKamsker** [comment]
+1 from me

**Comment by denjmpr** [comment]
Really saved me 5 days in the past.
Please, provide it for VS 2022.

**Comment by sascha-michalke** [comment]
I miss this extension in VS 2022 too. Please update! 👍

**Comment by EQMacQ** [comment]
100% agree ... need an updated version to support VS 2022

**Comment by guudan** [comment]
I updated the extension to new Visual Studio. You can find it under "Add Multiple Projects To Solution V2" name (there is a need to publish it separately).
